name: MyWorkflow File
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    - name: greeting steps
      run: |
        echo "Hello World"

    - name: Checkout my code
      uses: actions/checkout@v4
    - name: print content of Repo
      run: |
        ls
      
