name: MyWorkflow File
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    - name: greeting steps
      run: |
        echo "Hello World"

    # This is where I checkout my code
    - name: Checkout my code
      uses: actions/checkout@v4
    - name: print content of Repo
      run: |
        ls
      

    # This is where I install python
    - name: Installing Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: check version of python
    - run: |
        python --version
      
